### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sharonr78**
The top header and copyright were removed from the main help screen. 
All texts were validated by TW.

### CODE REVIEW

**Review by sgnn7 — APPROVED** [review]
@sharonr78 LGTM but do we want to link this in the main README too?

**Comment by sigalsax** [comment]
@sharonr78 is this still relevant?

**Comment by sharonr78** [comment]
> @sharonr78 is this still relevant?
Hey Sigal.. I think not any more
You can close this issue

**Comment by sigalsax** [comment]
closing as this is no longer relevant

**Pull request closed without merging**
